hw_14 was started
EasyCode-JavaScriptReact-v1/javascript-react-course-viskosa pull request #14
Opened 2018-07-14 17:35 UTC by viskosa

only task about render DOM was done

2018-07-17 14:10 UTC, OlegLustenko requested changes

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/index.html
> +					<input type="checkbox" name="checkbox44" id="checkbox44" class="checkbox"v/>
you have a type, please check input attributes

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/index.html
> +			<div class="question-block">
Have you heard about BEM notation?

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/main.js
> +let myParser = new Parser();
wow :) You used a class here, it wasn't necessary

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/main.js
> +													{
Why there a lot of tab/spaces ? it looks weird
![image](https://user-images.githubusercontent.com/11524061/42797967-8117a5f4-899a-11e8-925c-ce8e7b750b09.png)

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/main.js
> +class app {
the class should be named from upperCase

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/main.js
> +	createElement(options) {
very nice decision to make additional method to create element I like it

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/main.js
> +		let {node, className, typeAttr, nameAttr, idAttr, forAttr, actionAttr, methodAttr, valueAttr, nodeValue} = options;
this is a very very long line looks strange.
Please install prettier and format you code with it

2018-07-17 14:10 UTC, OlegLustenko commented on js-core/homeworks/homework-14/main.js
> +		return elem;
you know, the idea to make an additional method to create elements very nice, but you have to worry about the responsibilities of such a method.

For example, your method does not just create an element he know a lot about your application and usage.

He accepts a lot of params.

Your method responsible to:
- accept tagName
- accept and than apply attributes from "white-list"
- set value to a newly created element

So if it has only 1 responsibility it would be very cool! It could be reusable in any application in future, but now he is bound with implementation.

As a solution, you could make for example one more, or "few more" method which would have other responsibilities they will be smaller but still efficient

2018-07-19 13:31 UTC, viskosa commented on js-core/homeworks/homework-14/index.html
> +					<input type="checkbox" name="checkbox44" id="checkbox44" class="checkbox"v/>
what do you mean?

2018-07-19 14:08 UTC, viskosa commented
Fixed a bit

2018-07-22 04:27 UTC, merged